import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";
import { ThemeProvider } from "next-themes";
import { NextIntlClientProvider } from "next-intl";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Plan4",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-zinc-900 transition-colors duration-200`}
      >
        <NextIntlClientProvider>
          <ThemeProvider
            attribute="class"
            enableSystem
            defaultTheme="dark"
          >
            <Header />
            <main className="min-h-screen bg-white dark:bg-zinc-900 text-black dark:text-white transition-colors duration-200">

              {children}

            </main>


          </ThemeProvider>
        </NextIntlClientProvider>

      </body>

    </html>
  );
}